baseURL = "/"
languageCode = "en-us"
title = "Redwood Reviews"
theme = "PaperMod"

[params]
  author = "Cade & Cooper"
  ShowReadingTime = true

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Subscribe"
  url = "/subscribe/"
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


